-- =====================================================================
-- AnniversaryGifts — schema `anniversarygifts` (a app das prendas de anos).
-- Correr no SQL Editor do Supabase (o MESMO projeto das outras apps).
-- É IDEMPOTENTE: pode correr mais que uma vez sem erro.
--
-- Depois de correr: Settings → API → Exposed schemas → acrescentar
-- `anniversarygifts`. Sem isso o PostgREST responde 406/404 a tudo.
--
-- O MODELO, numa frase: cada amigo tem um dia de anos; ordenados pelo
-- calendário formam um CICLO, e quem faz anos imediatamente antes é quem
-- compra a garrafa para o seguinte. O custo divide-se por todos os outros
-- (incluindo quem compra), NUNCA por quem faz anos.
--
-- As escritas em `eventos` e `pagamentos` passam SÓ por funções SECURITY
-- DEFINER (mais abaixo): as regras de quem pode o quê vivem aqui, num sítio
-- só, e não em policies espalhadas. A leitura é aberta a quem tem acesso —
-- as dívidas são PÚBLICAS dentro do grupo, de propósito.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS anniversarygifts;
GRANT USAGE ON SCHEMA anniversarygifts TO anon, authenticated, service_role;

-- ── Configuração (chave/valor) ────────────────────────────────────────
-- `admin_email`: quem gere amigos, datas e acessos.
-- `inicio`: desde quando o grupo faz isto (a app propõe registar as prendas
--           de aniversários a partir desta data — os eventos passados).
CREATE TABLE IF NOT EXISTS anniversarygifts.config (
  chave         text PRIMARY KEY,
  valor         jsonb NOT NULL DEFAULT '{}'::jsonb,
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
INSERT INTO anniversarygifts.config (chave, valor)
VALUES ('admin_email', to_jsonb('diogo.andre.f.silva@gmail.com'::text))
ON CONFLICT (chave) DO NOTHING;
-- O PREÇO é sempre opcional: registar a garrafa e gerir as contas pela app
-- são coisas separadas, e a segunda é com cada um. Sem preço ninguém deve
-- nada. (Houve uma `preco_obrigatorio_desde` a obrigá-lo daqui em diante;
-- saiu a pedido do dono.)
DELETE FROM anniversarygifts.config WHERE chave = 'preco_obrigatorio_desde';

-- ── Amigos ────────────────────────────────────────────────────────────
-- O NOME é a identidade (é o que aparece nas prendas e nos pagamentos), o
-- email liga-o a uma conta. Ter email aqui É o acesso à app: não há uma
-- `allowed_users` à parte — dois sítios a dizer quem é do grupo divergiam.
-- `dia`/`mes` sem ano: só interessa quando calha. Sem data, o amigo fica
-- fora do ciclo (mas pode continuar a dever/receber de prendas antigas).
CREATE TABLE IF NOT EXISTS anniversarygifts.amigos (
  nome      text PRIMARY KEY CHECK (btrim(nome) <> ''),
  email     text,
  dia       smallint CHECK (dia BETWEEN 1 AND 31),
  mes       smallint CHECK (mes BETWEEN 1 AND 12),
  ativo     boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CHECK ((dia IS NULL) = (mes IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS amigos_email_uq
  ON anniversarygifts.amigos (lower(email)) WHERE email IS NOT NULL;

-- ── Pedidos de acesso ─────────────────────────────────────────────────
-- Quem entra com uma conta que ainda não está ligada a nenhum amigo. O
-- admin liga-a a um nome (Definições) e o pedido desaparece.
CREATE TABLE IF NOT EXISTS anniversarygifts.access_requests (
  email        text PRIMARY KEY,
  requested_at timestamptz NOT NULL DEFAULT now()
);

-- ── Eventos: uma prenda por aniversário ───────────────────────────────
-- `participantes` é uma FOTOGRAFIA de quem divide esta prenda (inclui quem
-- compra, nunca quem faz anos). Fotografia e não "os amigos ativos": o
-- grupo muda, e uma prenda de março não pode passar a dividir-se por quem
-- entrou em setembro.
-- `vinho` é a ficha da garrafa (nome, produtor, ano, região, castas, nota,
-- preço de mercado, …) — ver `app.js`, secção O VINHO.
CREATE TABLE IF NOT EXISTS anniversarygifts.eventos (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aniversariante text NOT NULL REFERENCES anniversarygifts.amigos(nome) ON UPDATE CASCADE,
  data           date NOT NULL,
  ano            integer GENERATED ALWAYS AS (extract(year FROM data)::integer) STORED,
  responsavel    text NOT NULL REFERENCES anniversarygifts.amigos(nome) ON UPDATE CASCADE,
  participantes  text[] NOT NULL DEFAULT '{}',
  estado         text NOT NULL DEFAULT 'comprado'
                   CHECK (estado IN ('comprado', 'entregue')),
  valor          numeric(10,2) CHECK (valor IS NULL OR valor >= 0),
  vinho          jsonb NOT NULL DEFAULT '{}'::jsonb,
  notas          text,
  criado_por     text,
  criado_em      timestamptz NOT NULL DEFAULT now(),
  atualizado_por text,
  atualizado_em  timestamptz NOT NULL DEFAULT now(),
  CHECK (aniversariante <> responsavel),
  CONSTRAINT eventos_um_por_ano UNIQUE (aniversariante, ano)
);

-- ── Pagamentos ────────────────────────────────────────────────────────
-- O fluxo do SplitBill: quem deve DECLARA que pagou, quem recebeu ACEITA
-- ou RECUSA. Quem recebeu também pode registar diretamente "recebi" (nasce
-- já confirmado). Só os confirmados abatem à dívida.
CREATE TABLE IF NOT EXISTS anniversarygifts.pagamentos (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id     bigint NOT NULL REFERENCES anniversarygifts.eventos(id) ON DELETE CASCADE,
  devedor       text NOT NULL,
  credor        text NOT NULL,
  valor         numeric(10,2) NOT NULL CHECK (valor > 0),
  estado        text NOT NULL DEFAULT 'declarado'
                  CHECK (estado IN ('declarado', 'confirmado', 'recusado')),
  nota          text,
  criado_por    text,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  resolvido_por text,
  resolvido_em  timestamptz
);
-- O LIMITE: as prendas têm um valor máximo combinado. Quem escolhe gastar
-- mais normalmente fica com o excedente — por isso o que se DIVIDE pode ser
-- menos do que o que se PAGOU. `valor_dividir` é essa parte (NULL = divide-se
-- o preço todo); o resto fica com quem comprou. O limite em si vive em
-- `config.limite_prenda` e é só a PROPOSTA: quem regista pode dividir mais
-- ou menos, porque "normalmente" não é "sempre".
ALTER TABLE anniversarygifts.eventos ADD COLUMN IF NOT EXISTS valor_dividir numeric(10,2)
  CHECK (valor_dividir IS NULL OR valor_dividir >= 0);

CREATE INDEX IF NOT EXISTS pagamentos_evento_idx ON anniversarygifts.pagamentos (evento_id);

-- ── Notificações push (uma linha por dispositivo) ─────────────────────
-- Tabela própria e não a do SplitBill: a subscription nasce do service
-- worker DESTA app (outro scope), por isso é outra.
CREATE TABLE IF NOT EXISTS anniversarygifts.push_subscriptions (
  endpoint   text PRIMARY KEY,
  email      text NOT NULL,
  p256dh     text NOT NULL,
  auth_key   text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS push_subscriptions_email_idx
  ON anniversarygifts.push_subscriptions (lower(email));

-- =====================================================================
-- QUEM SOU EU
-- =====================================================================
CREATE OR REPLACE FUNCTION anniversarygifts.meu_email() RETURNS text
  LANGUAGE sql STABLE
AS $$ SELECT lower(coalesce(auth.jwt() ->> 'email', '')) $$;

CREATE OR REPLACE FUNCTION anniversarygifts.is_admin() RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
  SELECT anniversarygifts.meu_email() <> '' AND EXISTS (
    SELECT 1 FROM anniversarygifts.config
     WHERE chave = 'admin_email' AND lower(valor #>> '{}') = anniversarygifts.meu_email())
$$;

-- O nome do amigo ligado à conta com sessão (NULL se não houver).
CREATE OR REPLACE FUNCTION anniversarygifts.eu() RETURNS text
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
  SELECT nome FROM anniversarygifts.amigos
   WHERE email IS NOT NULL AND lower(email) = anniversarygifts.meu_email()
   LIMIT 1
$$;

CREATE OR REPLACE FUNCTION anniversarygifts.is_allowed() RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$ SELECT anniversarygifts.is_admin() OR anniversarygifts.eu() IS NOT NULL $$;

-- O que a app pergunta logo a seguir ao login.
CREATE OR REPLACE FUNCTION anniversarygifts.acesso() RETURNS jsonb
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
  SELECT jsonb_build_object(
    'email', anniversarygifts.meu_email(),
    'permitido', anniversarygifts.is_allowed(),
    'admin', anniversarygifts.is_admin(),
    'eu', anniversarygifts.eu())
$$;

-- =====================================================================
-- AS DÍVIDAS — uma só fonte de cêntimos
-- Lição paga no SplitBill: três contas diferentes para a mesma pergunta
-- davam a mesma pessoa a 17.50 num ecrã e 17.51 noutro. Aqui a quota de
-- cada um sai SÓ desta view — a app e a Edge Function das notificações
-- leem-na, nenhuma recalcula. Quem compra não aparece (não deve nada a si
-- próprio) e absorve o cêntimo que sobrar do arredondamento.
-- `security_invoker = false`: corre como o dono, porque quem tem login já
-- não lê a `eventos` direto (ver eventos_v); o portão é o is_allowed().
-- O portão deixa passar também a service role: a `prendas-notificar` lê
-- aqui com ela, e a service role não tem `eu()` — só com o is_allowed() a
-- view dava-lhe zero linhas e os avisos de dívida não saíam para ninguém.
-- =====================================================================
CREATE OR REPLACE VIEW anniversarygifts.dividas WITH (security_invoker = false) AS
SELECT e.id AS evento_id,
       p.devedor,
       e.responsavel AS credor,
       round(coalesce(e.valor_dividir, e.valor) / greatest(cardinality(e.participantes), 1), 2) AS quota,
       coalesce(sum(pg.valor) FILTER (WHERE pg.estado = 'confirmado'), 0) AS pago,
       coalesce(sum(pg.valor) FILTER (WHERE pg.estado = 'declarado'), 0)  AS por_confirmar,
       round(coalesce(e.valor_dividir, e.valor) / greatest(cardinality(e.participantes), 1), 2)
         - coalesce(sum(pg.valor) FILTER (WHERE pg.estado = 'confirmado'), 0) AS saldo
  FROM anniversarygifts.eventos e
 CROSS JOIN LATERAL unnest(e.participantes) AS p(devedor)
  LEFT JOIN anniversarygifts.pagamentos pg
         ON pg.evento_id = e.id AND pg.devedor = p.devedor
 WHERE coalesce(e.valor_dividir, e.valor) > 0
   AND p.devedor <> e.responsavel
   AND (anniversarygifts.is_allowed() OR auth.role() = 'service_role')
 GROUP BY e.id, p.devedor, e.responsavel, e.valor, e.valor_dividir, e.participantes;

-- =====================================================================
-- ESCRITAS (SECURITY DEFINER). Cada uma confirma quem chama.
-- ATENÇÃO aos NULL: com `eu()` a NULL, `NOT (false OR NULL)` é NULL e um
-- IF NULL NÃO entra no RAISE — deixava passar. Toda a verificação de
-- permissão vai dentro de coalesce(…, false).
-- =====================================================================

-- Criar (p_id NULL) ou alterar uma prenda.
-- Quem: o admin, ou o RESPONSÁVEL pela prenda. O responsável não pode
-- mudar o aniversariante nem passar a responsabilidade a outro — isso é
-- decisão do admin (é o ciclo, não a vontade de quem compra).
-- (a assinatura antiga, sem p_valor_dividir, sai: duas versões da mesma
-- função eram duas portas com regras diferentes)
DROP FUNCTION IF EXISTS anniversarygifts.guardar_evento(bigint, text, date, text, text[], text, numeric, jsonb, text);
CREATE OR REPLACE FUNCTION anniversarygifts.guardar_evento(
  p_id bigint, p_aniversariante text, p_data date, p_responsavel text,
  p_participantes text[], p_estado text, p_valor numeric, p_vinho jsonb, p_notas text,
  p_valor_dividir numeric DEFAULT NULL
) RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
DECLARE
  v_eu    text    := anniversarygifts.eu();
  v_admin boolean := anniversarygifts.is_admin();
  v_part  text[];
  v_antes numeric;
  v_div   numeric;
  r       anniversarygifts.eventos%ROWTYPE;
BEGIN
  IF NOT anniversarygifts.is_allowed() THEN RAISE EXCEPTION 'Sem acesso.'; END IF;
  IF p_aniversariante IS NULL OR p_responsavel IS NULL OR p_data IS NULL THEN
    RAISE EXCEPTION 'Faltam o aniversariante, o responsável ou a data.';
  END IF;
  IF p_aniversariante = p_responsavel THEN
    RAISE EXCEPTION 'Quem faz anos não compra a própria prenda.';
  END IF;
  IF p_valor IS NOT NULL AND p_valor < 0 THEN RAISE EXCEPTION 'Valor inválido.'; END IF;
  -- O que se divide nunca passa do que se pagou; sem preço não há nada a dividir.
  v_div := CASE WHEN coalesce(p_valor, 0) > 0 THEN p_valor_dividir END;
  IF v_div IS NOT NULL AND (v_div < 0 OR v_div > p_valor) THEN
    RAISE EXCEPTION 'O valor a dividir não pode passar do preço pago.';
  END IF;
  IF v_div = p_valor THEN v_div := NULL; END IF;
  IF p_vinho IS NOT NULL AND (jsonb_typeof(p_vinho) <> 'object' OR length(p_vinho::text) > 20000) THEN
    RAISE EXCEPTION 'Ficha do vinho inválida.';
  END IF;

  -- Quem divide: sem repetidos, NUNCA quem faz anos, SEMPRE quem compra.
  SELECT coalesce(array_agg(DISTINCT x ORDER BY x), '{}') INTO v_part
    FROM unnest(coalesce(p_participantes, '{}') || p_responsavel) x
   WHERE x IS NOT NULL AND btrim(x) <> '' AND x <> p_aniversariante;
  IF EXISTS (SELECT 1 FROM unnest(v_part) x
              WHERE NOT EXISTS (SELECT 1 FROM anniversarygifts.amigos a WHERE a.nome = x)) THEN
    RAISE EXCEPTION 'Há participantes que não estão na lista de amigos.';
  END IF;

  IF p_id IS NULL THEN
    IF NOT coalesce(v_admin OR v_eu = p_responsavel, false) THEN
      RAISE EXCEPTION 'Só quem compra a prenda (ou o admin) a pode registar.';
    END IF;
    -- A garrafa é SURPRESA para quem faz anos (ver eventos_v): nem o admin
    -- regista a sua própria — veria o que lhe vão dar.
    IF v_eu = p_aniversariante THEN
      RAISE EXCEPTION 'A tua própria prenda regista-a quem ta compra — é surpresa.';
    END IF;
    BEGIN
      INSERT INTO anniversarygifts.eventos
        (aniversariante, data, responsavel, participantes, estado, valor, valor_dividir, vinho, notas, criado_por, atualizado_por)
      VALUES (p_aniversariante, p_data, p_responsavel, v_part, coalesce(p_estado, 'comprado'),
              p_valor, v_div, coalesce(p_vinho, '{}'::jsonb), nullif(btrim(coalesce(p_notas, '')), ''),
              anniversarygifts.meu_email(), anniversarygifts.meu_email())
      RETURNING * INTO r;
    EXCEPTION WHEN unique_violation THEN
      RAISE EXCEPTION 'Já existe uma prenda para os anos de % em %.', p_aniversariante, extract(year FROM p_data);
    END;
    RETURN to_jsonb(r) || jsonb_build_object('valor_mudou', coalesce(v_div, p_valor, 0) > 0);
  END IF;

  SELECT * INTO r FROM anniversarygifts.eventos WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Esta prenda já não existe.'; END IF;
  IF NOT coalesce(v_admin OR v_eu = r.responsavel, false) THEN
    RAISE EXCEPTION 'Só quem comprou a prenda (ou o admin) a pode alterar.';
  END IF;
  IF NOT v_admin AND (p_aniversariante IS DISTINCT FROM r.aniversariante
                      OR p_responsavel IS DISTINCT FROM r.responsavel) THEN
    RAISE EXCEPTION 'Só o admin muda quem faz anos ou quem compra.';
  END IF;
  -- Quem faz anos não mexe na prenda antes de a receber: a app mostra-lhe a
  -- ficha VAZIA (eventos_v), e gravar por cima apagava a garrafa.
  IF v_eu = r.aniversariante AND r.estado <> 'entregue' THEN
    RAISE EXCEPTION 'Esta prenda é tua — só lhe podes mexer depois de a receberes.';
  END IF;
  v_antes := coalesce(r.valor_dividir, r.valor);

  BEGIN
    UPDATE anniversarygifts.eventos SET
      aniversariante = p_aniversariante, data = p_data, responsavel = p_responsavel,
      participantes = v_part, estado = coalesce(p_estado, estado), valor = p_valor, valor_dividir = v_div,
      vinho = coalesce(p_vinho, vinho), notas = nullif(btrim(coalesce(p_notas, '')), ''),
      atualizado_por = anniversarygifts.meu_email(), atualizado_em = now()
    WHERE id = p_id
    RETURNING * INTO r;
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION 'Já existe uma prenda para os anos de % em %.', p_aniversariante, extract(year FROM p_data);
  END;
  RETURN to_jsonb(r) || jsonb_build_object(
    'valor_mudou', coalesce(v_div, p_valor, 0) > 0 AND coalesce(v_div, p_valor) IS DISTINCT FROM v_antes);
END;
$$;

-- Apagar: o admin sempre; o responsável só enquanto ninguém lhe pagou
-- (senão apagava de caminho os pagamentos confirmados de outras pessoas).
CREATE OR REPLACE FUNCTION anniversarygifts.apagar_evento(p_id bigint) RETURNS void
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
DECLARE r anniversarygifts.eventos%ROWTYPE;
BEGIN
  SELECT * INTO r FROM anniversarygifts.eventos WHERE id = p_id;
  IF NOT FOUND THEN RETURN; END IF;
  IF NOT anniversarygifts.is_admin() THEN
    IF anniversarygifts.eu() IS DISTINCT FROM r.responsavel THEN
      RAISE EXCEPTION 'Só o admin ou quem comprou a prenda a pode apagar.';
    END IF;
    IF EXISTS (SELECT 1 FROM anniversarygifts.pagamentos WHERE evento_id = p_id AND estado = 'confirmado') THEN
      RAISE EXCEPTION 'Já há pagamentos confirmados nesta prenda — só o admin a pode apagar.';
    END IF;
  END IF;
  DELETE FROM anniversarygifts.eventos WHERE id = p_id;
END;
$$;

-- "Já paguei" — declarado por quem deve (ou pelo admin em nome de alguém).
CREATE OR REPLACE FUNCTION anniversarygifts.declarar_pagamento(
  p_evento bigint, p_valor numeric, p_devedor text DEFAULT NULL, p_nota text DEFAULT NULL
) RETURNS bigint
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
DECLARE
  v_eu text := anniversarygifts.eu();
  v_devedor text := coalesce(nullif(btrim(coalesce(p_devedor, '')), ''), v_eu);
  r anniversarygifts.eventos%ROWTYPE;
  v_id bigint;
BEGIN
  IF NOT anniversarygifts.is_allowed() THEN RAISE EXCEPTION 'Sem acesso.'; END IF;
  IF v_devedor IS NULL THEN RAISE EXCEPTION 'A tua conta não está ligada a nenhum amigo.'; END IF;
  IF v_devedor IS DISTINCT FROM v_eu AND NOT anniversarygifts.is_admin() THEN
    RAISE EXCEPTION 'Só podes declarar os teus próprios pagamentos.';
  END IF;
  IF p_valor IS NULL OR p_valor <= 0 THEN RAISE EXCEPTION 'Valor inválido.'; END IF;
  SELECT * INTO r FROM anniversarygifts.eventos WHERE id = p_evento;
  IF NOT FOUND THEN RAISE EXCEPTION 'Esta prenda já não existe.'; END IF;
  IF NOT v_devedor = ANY(r.participantes) OR v_devedor = r.responsavel THEN
    RAISE EXCEPTION '% não deve nada nesta prenda.', v_devedor;
  END IF;
  IF EXISTS (SELECT 1 FROM anniversarygifts.pagamentos
              WHERE evento_id = p_evento AND devedor = v_devedor AND estado = 'declarado') THEN
    RAISE EXCEPTION 'Já há um pagamento teu à espera de confirmação nesta prenda.';
  END IF;
  INSERT INTO anniversarygifts.pagamentos (evento_id, devedor, credor, valor, estado, nota, criado_por)
  VALUES (p_evento, v_devedor, r.responsavel, round(p_valor, 2), 'declarado',
          nullif(btrim(coalesce(p_nota, '')), ''), anniversarygifts.meu_email())
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

-- "Recebi" — registado diretamente por quem recebeu (nasce confirmado).
CREATE OR REPLACE FUNCTION anniversarygifts.registar_recebido(
  p_evento bigint, p_devedor text, p_valor numeric
) RETURNS bigint
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
DECLARE r anniversarygifts.eventos%ROWTYPE; v_id bigint;
BEGIN
  SELECT * INTO r FROM anniversarygifts.eventos WHERE id = p_evento;
  IF NOT FOUND THEN RAISE EXCEPTION 'Esta prenda já não existe.'; END IF;
  IF NOT coalesce(anniversarygifts.is_admin() OR anniversarygifts.eu() = r.responsavel, false) THEN
    RAISE EXCEPTION 'Só quem comprou a prenda (ou o admin) regista o que recebeu.';
  END IF;
  IF p_valor IS NULL OR p_valor <= 0 THEN RAISE EXCEPTION 'Valor inválido.'; END IF;
  IF NOT p_devedor = ANY(r.participantes) OR p_devedor = r.responsavel THEN
    RAISE EXCEPTION '% não deve nada nesta prenda.', p_devedor;
  END IF;
  -- Um "já paguei" pendente da mesma pessoa fica resolvido por este.
  UPDATE anniversarygifts.pagamentos
     SET estado = 'recusado', resolvido_por = anniversarygifts.meu_email(), resolvido_em = now(),
         nota = coalesce(nota || ' · ', '') || 'substituído por um registo de quem recebeu'
   WHERE evento_id = p_evento AND devedor = p_devedor AND estado = 'declarado';
  INSERT INTO anniversarygifts.pagamentos
    (evento_id, devedor, credor, valor, estado, criado_por, resolvido_por, resolvido_em)
  VALUES (p_evento, p_devedor, r.responsavel, round(p_valor, 2), 'confirmado',
          anniversarygifts.meu_email(), anniversarygifts.meu_email(), now())
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

-- "Este já pagou" / "afinal não pagou" — quem comprou (ou o admin), sobretudo
-- ao REGISTAR uma prenda passada: marca-se logo quem já tinha pago, antes de
-- sair qualquer aviso, para ninguém ser notificado por uma dívida que já não
-- existe. Marcar = a conta dessa pessoa fica EXATAMENTE a zero: o "já paguei"
-- pendente (que pode ter outro valor) sai, e entra um confirmado pelo saldo
-- da view. Desmarcar = apaga os pagamentos dessa pessoa nesta prenda.
CREATE OR REPLACE FUNCTION anniversarygifts.marcar_pago(p_evento bigint, p_devedor text, p_pago boolean)
  RETURNS void
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
DECLARE r anniversarygifts.eventos%ROWTYPE; v_saldo numeric;
BEGIN
  SELECT * INTO r FROM anniversarygifts.eventos WHERE id = p_evento;
  IF NOT FOUND THEN RAISE EXCEPTION 'Esta prenda já não existe.'; END IF;
  IF NOT coalesce(anniversarygifts.is_admin() OR anniversarygifts.eu() = r.responsavel, false) THEN
    RAISE EXCEPTION 'Só quem comprou a prenda (ou o admin) marca quem já pagou.';
  END IF;
  IF NOT p_devedor = ANY(r.participantes) OR p_devedor = r.responsavel THEN
    RAISE EXCEPTION '% não deve nada nesta prenda.', p_devedor;
  END IF;
  IF NOT p_pago THEN
    DELETE FROM anniversarygifts.pagamentos WHERE evento_id = p_evento AND devedor = p_devedor;
    RETURN;
  END IF;
  DELETE FROM anniversarygifts.pagamentos
   WHERE evento_id = p_evento AND devedor = p_devedor AND estado <> 'confirmado';
  SELECT saldo INTO v_saldo FROM anniversarygifts.dividas
   WHERE evento_id = p_evento AND devedor = p_devedor;
  IF coalesce(v_saldo, 0) > 0 THEN
    INSERT INTO anniversarygifts.pagamentos
      (evento_id, devedor, credor, valor, estado, nota, criado_por, resolvido_por, resolvido_em)
    VALUES (p_evento, p_devedor, r.responsavel, v_saldo, 'confirmado', 'marcado como pago por quem recebeu',
            anniversarygifts.meu_email(), anniversarygifts.meu_email(), now());
  END IF;
END;
$$;

-- Aceitar ou recusar um "já paguei".
CREATE OR REPLACE FUNCTION anniversarygifts.resolver_pagamento(p_id bigint, p_aceitar boolean)
  RETURNS void
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
DECLARE p anniversarygifts.pagamentos%ROWTYPE; v_resp text;
BEGIN
  SELECT * INTO p FROM anniversarygifts.pagamentos WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Este pagamento já não existe.'; END IF;
  SELECT responsavel INTO v_resp FROM anniversarygifts.eventos WHERE id = p.evento_id;
  IF NOT coalesce(anniversarygifts.is_admin() OR anniversarygifts.eu() IN (p.credor, v_resp), false) THEN
    RAISE EXCEPTION 'Só quem recebeu (ou o admin) confirma um pagamento.';
  END IF;
  IF p.estado <> 'declarado' THEN RAISE EXCEPTION 'Este pagamento já foi resolvido.'; END IF;
  UPDATE anniversarygifts.pagamentos
     SET estado = CASE WHEN p_aceitar THEN 'confirmado' ELSE 'recusado' END,
         resolvido_por = anniversarygifts.meu_email(), resolvido_em = now()
   WHERE id = p_id;
END;
$$;

-- Desfazer: quem declarou tira o seu enquanto não for aceite; quem recebeu
-- (ou o admin) pode tirar qualquer um — é o "enganei-me".
CREATE OR REPLACE FUNCTION anniversarygifts.anular_pagamento(p_id bigint) RETURNS void
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
DECLARE p anniversarygifts.pagamentos%ROWTYPE; v_eu text := anniversarygifts.eu(); v_resp text;
BEGIN
  SELECT * INTO p FROM anniversarygifts.pagamentos WHERE id = p_id;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT responsavel INTO v_resp FROM anniversarygifts.eventos WHERE id = p.evento_id;
  IF NOT coalesce(anniversarygifts.is_admin() OR v_eu IN (p.credor, v_resp)
          OR (v_eu = p.devedor AND p.estado <> 'confirmado'), false) THEN
    RAISE EXCEPTION 'Não podes anular este pagamento.';
  END IF;
  DELETE FROM anniversarygifts.pagamentos WHERE id = p_id;
END;
$$;

-- Admin: ligar uma conta (email) a um amigo — é assim que se dá acesso.
CREATE OR REPLACE FUNCTION anniversarygifts.ligar_email(p_nome text, p_email text) RETURNS void
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
BEGIN
  IF NOT anniversarygifts.is_admin() THEN RAISE EXCEPTION 'Só o admin.'; END IF;
  UPDATE anniversarygifts.amigos SET email = nullif(lower(btrim(coalesce(p_email, ''))), '')
   WHERE nome = p_nome;
  IF NOT FOUND THEN RAISE EXCEPTION 'Não há nenhum amigo chamado %.', p_nome; END IF;
  DELETE FROM anniversarygifts.access_requests WHERE lower(email) = lower(btrim(p_email));
END;
$$;

-- =====================================================================
-- GRANTS — tabela a tabela (nada de GRANT ALL ON ALL TABLES).
-- =====================================================================
REVOKE ALL ON ALL TABLES IN SCHEMA anniversarygifts FROM anon;
-- eventos NÃO: lê-se pela eventos_v (a surpresa, no fim do ficheiro).
GRANT SELECT ON anniversarygifts.config, anniversarygifts.amigos,
                anniversarygifts.pagamentos, anniversarygifts.dividas TO authenticated;
GRANT INSERT, UPDATE, DELETE ON anniversarygifts.config, anniversarygifts.amigos TO authenticated;
GRANT SELECT, INSERT, DELETE ON anniversarygifts.access_requests TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON anniversarygifts.push_subscriptions TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA anniversarygifts TO service_role;

-- Cada função nova nasce com EXECUTE para PUBLIC — um REVOKE esquecido não
-- dá erro, dá uma porta aberta calada.
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA anniversarygifts FROM PUBLIC, anon;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA anniversarygifts TO authenticated, service_role;

-- =====================================================================
-- RLS
-- =====================================================================
ALTER TABLE anniversarygifts.config             ENABLE ROW LEVEL SECURITY;
ALTER TABLE anniversarygifts.amigos             ENABLE ROW LEVEL SECURITY;
ALTER TABLE anniversarygifts.access_requests    ENABLE ROW LEVEL SECURITY;
ALTER TABLE anniversarygifts.eventos            ENABLE ROW LEVEL SECURITY;
ALTER TABLE anniversarygifts.pagamentos         ENABLE ROW LEVEL SECURITY;
ALTER TABLE anniversarygifts.push_subscriptions ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  -- Ler: quem tem acesso vê tudo (as dívidas são públicas no grupo).
  FOREACH t IN ARRAY ARRAY['config', 'amigos', 'eventos', 'pagamentos'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON anniversarygifts.%I', t || '_ler', t);
    EXECUTE format('CREATE POLICY %I ON anniversarygifts.%I FOR SELECT TO authenticated USING (anniversarygifts.is_allowed())', t || '_ler', t);
  END LOOP;
  -- Escrever amigos e config: só o admin. Eventos e pagamentos: só por RPC.
  FOREACH t IN ARRAY ARRAY['config', 'amigos'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON anniversarygifts.%I', t || '_admin', t);
    EXECUTE format('CREATE POLICY %I ON anniversarygifts.%I FOR ALL TO authenticated USING (anniversarygifts.is_admin()) WITH CHECK (anniversarygifts.is_admin())', t || '_admin', t);
  END LOOP;
END $$;

DROP POLICY IF EXISTS access_requests_pedir ON anniversarygifts.access_requests;
CREATE POLICY access_requests_pedir ON anniversarygifts.access_requests
  FOR INSERT TO authenticated WITH CHECK (lower(email) = anniversarygifts.meu_email());
DROP POLICY IF EXISTS access_requests_admin_ler ON anniversarygifts.access_requests;
CREATE POLICY access_requests_admin_ler ON anniversarygifts.access_requests
  FOR SELECT TO authenticated USING (anniversarygifts.is_admin());
DROP POLICY IF EXISTS access_requests_admin_apagar ON anniversarygifts.access_requests;
CREATE POLICY access_requests_admin_apagar ON anniversarygifts.access_requests
  FOR DELETE TO authenticated USING (anniversarygifts.is_admin());

DROP POLICY IF EXISTS push_propria ON anniversarygifts.push_subscriptions;
CREATE POLICY push_propria ON anniversarygifts.push_subscriptions
  FOR ALL TO authenticated
  USING (lower(email) = anniversarygifts.meu_email())
  WITH CHECK (lower(email) = anniversarygifts.meu_email());

-- Confirmação (correr à parte): nenhuma função deste schema executável por anon.
--   SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
--    WHERE n.nspname = 'anniversarygifts' AND has_function_privilege('anon', p.oid, 'execute');

-- =====================================================================
-- A GARRAFA É SURPRESA
-- Quem faz anos não pode ver QUAL é a garrafa enquanto a prenda não estiver
-- "entregue" (as dívidas pode ver: o que custou não estraga a surpresa).
-- Esconder no ecrã não chegava — a tabela lia-se por REST e o `vinho` vinha
-- inteiro. Por isso:
--   · `eventos` deixa de ser legível por quem tem login;
--   · quem lê é a vista `eventos_v`, que corre como o dono e, para o próprio
--     aniversariante de uma prenda ainda não entregue, devolve o `vinho`
--     vazio e as `notas` a NULL (as notas podem dizer o vinho), com
--     `vinho_oculto = true` para a app saber mostrar "🎁 Surpresa";
--   · a `dividas` passou a `security_invoker = false` pela mesma razão (lê a
--     `eventos`), com o `is_allowed()` lá dentro;
--   · a `guardar_evento` recusa que quem faz anos registe ou mexa na sua
--     própria prenda antes de a receber (nem o admin).
-- O estado "por comprar" saiu (a pedido do dono): a prenda regista-se quando
-- a garrafa já foi comprada — "comprado" já serve para receber as partes.
-- =====================================================================
UPDATE anniversarygifts.eventos SET estado = 'comprado' WHERE estado = 'por_comprar';
ALTER TABLE anniversarygifts.eventos ALTER COLUMN estado SET DEFAULT 'comprado';
ALTER TABLE anniversarygifts.eventos DROP CONSTRAINT IF EXISTS eventos_estado_check;
ALTER TABLE anniversarygifts.eventos ADD CONSTRAINT eventos_estado_check CHECK (estado IN ('comprado', 'entregue'));

CREATE OR REPLACE VIEW anniversarygifts.eventos_v WITH (security_invoker = false) AS
SELECT e.id, e.aniversariante, e.data, e.ano, e.responsavel, e.participantes, e.estado,
       e.valor, e.valor_dividir,
       CASE WHEN o.oculto THEN '{}'::jsonb ELSE e.vinho END AS vinho,
       CASE WHEN o.oculto THEN NULL ELSE e.notas END AS notas,
       o.oculto AS vinho_oculto,
       e.criado_por, e.criado_em, e.atualizado_por, e.atualizado_em
  FROM anniversarygifts.eventos e
 CROSS JOIN LATERAL (SELECT coalesce(e.estado <> 'entregue'
                                      AND e.aniversariante = anniversarygifts.eu(), false) AS oculto) o
 WHERE anniversarygifts.is_allowed();

REVOKE SELECT ON anniversarygifts.eventos FROM authenticated, anon;
REVOKE ALL ON anniversarygifts.eventos_v FROM PUBLIC, anon;
GRANT SELECT ON anniversarygifts.eventos_v, anniversarygifts.dividas TO authenticated;


-- =====================================================================
-- PAINEL DO ADMIN: quem tem notificações e quando entrou pela última vez
-- `entradas`: a app regista-se aqui cada vez que abre (registar_entrada).
-- O `last_sign_in_at` do auth.users sozinho não servia: o projeto é o mesmo
-- das outras apps (um login no SplitBill contava como entrada aqui) e a
-- sessão renova-se sem login novo durante semanas. Fica só como recurso
-- para quem ainda não abriu a app desde que isto existe.
-- Ninguém lê a tabela por REST; só a `estado_amigos` (admin) a devolve.
-- =====================================================================
CREATE TABLE IF NOT EXISTS anniversarygifts.entradas (
  email  text PRIMARY KEY,
  ultima timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE anniversarygifts.entradas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON anniversarygifts.entradas FROM PUBLIC, anon, authenticated;
GRANT ALL ON anniversarygifts.entradas TO service_role;

CREATE OR REPLACE FUNCTION anniversarygifts.registar_entrada() RETURNS void
  LANGUAGE sql VOLATILE SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
  INSERT INTO anniversarygifts.entradas (email, ultima)
  SELECT anniversarygifts.meu_email(), now()
   WHERE anniversarygifts.meu_email() <> '' AND anniversarygifts.is_allowed()
  ON CONFLICT (email) DO UPDATE SET ultima = excluded.ultima
$$;

-- Uma linha por amigo: quantos dispositivos têm push e a última entrada.
-- `push_subscriptions` tem RLS "só as minhas", por isso é daqui que o admin
-- a vê; e o auth.users não é legível pela app de todo.
CREATE OR REPLACE FUNCTION anniversarygifts.estado_amigos()
  RETURNS TABLE (nome text, dispositivos int, ultima_entrada timestamptz, ultimo_login timestamptz)
  LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = anniversarygifts, public
AS $$
BEGIN
  IF NOT coalesce(anniversarygifts.is_admin(), false) THEN RAISE EXCEPTION 'Só o admin.'; END IF;
  RETURN QUERY
  SELECT a.nome,
         (SELECT count(*)::int FROM anniversarygifts.push_subscriptions s WHERE lower(s.email) = lower(a.email)),
         (SELECT e.ultima FROM anniversarygifts.entradas e WHERE e.email = lower(a.email)),
         (SELECT max(u.last_sign_in_at) FROM auth.users u WHERE lower(u.email) = lower(a.email))
    FROM anniversarygifts.amigos a
   WHERE a.email IS NOT NULL;
END;
$$;

REVOKE ALL ON FUNCTION anniversarygifts.registar_entrada(), anniversarygifts.estado_amigos() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION anniversarygifts.registar_entrada(), anniversarygifts.estado_amigos() TO authenticated, service_role;
